### ISSUE TITLE
Александр Титов Что такое DevOps Экспресс 42.md

### ISSUE THREAD

**Issue by fishca** [patsevanton/russian-conferences-articles#1]
Беру в работу.

**Comment by patsevanton** [comment]
Отлично

**Comment by gecube** [comment]
Не пора ли ишью закрыть, если все ОК? :-)

**Comment by patsevanton** [comment]
Я так понимаю issue, который открыл fishca - говорит о том, что он хотел расшифровать доклад Александра Титова "Что такое DevOps Экспресс 42"...

**Comment by gecube** [comment]
Я просто понял, что он уже расшифрован. Так ли это?

https://github.com/patsevanton/russian-conferences-articles/blob/master/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%20%D0%A2%D0%B8%D1%82%D0%BE%D0%B2%20%D0%A7%D1%82%D0%BE%20%D1%82%D0%B0%D0%BA%D0%BE%D0%B5%20DevOps%20%D0%AD%D0%BA%D1%81%D0%BF%D1%80%D0%B5%D1%81%D1%81%2042.md

**Comment by patsevanton** [comment]
Нет. Этот текст создан из субтитров. Там работы еще много

**Comment by patsevanton** [comment]
https://habr.com/ru/company/oleg-bunin/blog/448492/
